# Test Configurations from https://sighingnow.github.io/jekyll-gitbook/jekyll/2019-04-28-howto.html
title:            Jekyll Gitbook
longtitle:        Jekyll Gitbook
remote_theme:     sighingnow/jekyll-gitbook

#theme: jekyll-theme-tactile
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
